# This file includes the configuration parameters for fuzzing SymPy.

fuzzing:
  num: 100000
  total_time: 24
  log_level: 3
  otf: true
  resume: true
  evaluate: false
  use_hand_written_prompt: false
  no_input_prompt: false
  prompt_strategy: 2

target:
  language: sympy
  path_documentation: config/documentation/sympy/sympy_std.md
  path_example_code:
  trigger_to_generate_input: "'''Create SymPy programs that build symbolic expressions and apply transformations.'''"
  input_hint: "import sympy as sp\n"
  path_hand_written_prompt:
  target_string: "sp."
  oracle: simplify

llm:
  temperature: 1
  batch_size: 30
  device: cuda
  model_name: bigcode/starcoderbase
  max_length: 1024
